### ISSUE TITLE
Did you consider adding MyAnimeList synchronization ?

### ISSUE THREAD

**Issue by alaadotsol** [CindrInc/Kami-Desktop-Client#5]
The idea is pretty straight forward, I hope you can add Sync in between the app and the MAL server.
Here's their API : https://myanimelist.net/modules.php?go=api
Thanks !

**Comment by IshanArya** [comment]
Yes. That's the plan after putting more sources. Just for clarification, what does MAL/Kitsu allow you to do? What type of functionality do you want from it?

Also, this request is a duplicate, so I'm going to close it.
#4
